name: Deploy Docs

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - name: Checkout
      #   with:
      #     ref: ${{ github.event.inputs.branch || 'master' }}
      - uses: actions/checkout@v2
      - name: Build and deploy
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: ./deploy.sh